# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-gbcontainer-31

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: crmkd31.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_3C9372C3089C41B1BA97D94C84123788 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_0679779762D94EC7875E0B0FDA8EECE3 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: crmkd31.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_3C9372C3089C41B1BA97D94C84123788 }}/guestbook:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-gbcontainer-31'
          slot-name: 'staging'
          images: 'crmkd31.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_3C9372C3089C41B1BA97D94C84123788 }}/guestbook:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8A6C3AF5726F49E9A08DDDED14B4F8A3 }}